name: message_box
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  home_widget: ^0.8.0
  flutter_localizations:
    sdk: flutter
  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # Routing
  go_router: ^14.2.0
  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  tutorial_coach_mark: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter_native_splash:
  color: "#ffffff"        # màu nền splash
  image: assets/images/splash.png  # logo hoặc icon app
  android: true
  ios: true


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/guide/
    - assets/lottie/
  fonts:
    - family: ShantellSans
      fonts:
        - asset: assets/fonts/ShantellSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ShantellSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ShantellSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ShantellSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ShantellSans-SemiBold.ttf
          weight: 600  